hint.redoneX=Redone %q
spawnmenu.utilities.redo=Redo
spawnmenu.utilities.redo.help=Redo a previous action.
spawnmenu.utitilies.redo.velocity=Restore Entity Velocity
spawnmenu.utitilies.redo.constraints=Restore Constrained Entity Positions
spawnmenu.utilities.redo.help.constraints=For tight constraints like welds, this will restore the relative positions of the constrained entities.